### ISSUE TITLE
HDF5-UDF as a library?

### ISSUE THREAD

**Issue by angel-devicente** [lucasvr/hdf5-udf#12]
Hi,

I just started playing with HDF5-UDF and is really cool. But having to add UDFs always from the command line is a bit limiting. 

I think it would be great to try to create a library that can be called from inside a program. So, for example, from within Python I could have a script that writes an HDF5 file and some datasets, and from the same script I could add UDFs to the file. 

We have an application that generates HDF5 files, and for which I would always like to add some UDFs. Being able to do it from inside the application itself would be more convenient and less error-prone.

But I have no idea if this entails a lot of work...

**Comment by lucasvr** [comment]
Hi!

There is an ongoing work to rearrange the logic behind the main program so it can be used by new utilities. Shipping that code as a library should be a natural extension.

I will update this ticket with some design notes as the library comes to form.

**Comment by lucasvr** [comment]
We have a library! The API is defined on  [hdf5-udf.h](https://github.com/lucasvr/hdf5-udf/blob/master/src/hdf5-udf.h). The [main utility](https://github.com/lucasvr/hdf5-udf/blob/master/src/main.cpp#L96) is currently its sole user and serves as an example of how to use the API.

It would be interesting to have Python bindings at some point, but that's currently low on my priority list. I'll open a ticket just in case someone wants to volunteer.
