### ISSUE TITLE
modify_elf_section: /bin/bash: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by gheber** [lucasvr/hdf5-udf#18]
Please change `#!/bin/bash` to `#!/usr/bin/env bash` in `src/modify_elf_section`. Otherwise this fails on, for example, GNU Guix.

**Comment by lucasvr** [comment]
Thanks for the bug report. This one has just been fixed by 1b4b09c4c3ab049896765e45a0811b87a74d9b6c.
