### ISSUE TITLE
Missing include in code generated from cpp_backed.cpp

### ISSUE THREAD

**Issue by gheber** [lucasvr/hdf5-udf#19]
I believe around line 67 in `src/cpp_backend.cpp` there is an include missing to deal with the varargs, e.g.,
```
methods_impl += "#include <stdarg.h>\n";
```
There might be a better place, though.

Otherwise, some of the tests don't pass, e.g., `test-string.cpp`.

**Comment by gheber** [comment]
Also, `test/run_tests.sh` could use a `#!/usr/bin/env bash`.

**Comment by lucasvr** [comment]
Thanks for the heads up! Both have been fixed now.
