### ISSUE TITLE
Create .deb file

### ISSUE THREAD

**Issue by lucasvr** [lucasvr/hdf5-udf#3]
Create .deb file so that UDF5-HDF can be easily installed on Debian and Ubuntu-based distros.

**Comment by snhardin** [comment]
Happy Hacktoberfest! I would like to help with this issue. I have some background in building debian packages.

**Comment by lucasvr** [comment]
Sounds good! I hope it's not gonna be so complicated. As you can see in `INSTALL.md` and `src/Makefile`, there are a few dependencies that have to be met (libhdf5, libseccomp, luajit, and syscall-intercept). The latter seems to have no official package, so it would likely have to be cloned and built from the git repos directly. I don't know which kind of support Debian provides for building straight from git. The other minor challenge is that one of the dependencies is a PIP package (the CFFI module). I'm not sure how to handle that in a .deb file too.

**Comment by snhardin** [comment]
> Sounds good! I hope it's not gonna be so complicated.

Debian packages are never straightforward. It's part of the fun of trying to create one. 😉

I got your project building in a docker container! I initially tried to build this on the latest stable release of Debian, but I think the version of libseccomp may be too outdated to build your project. I didn't try Debian Sid. Ubuntu 20.04 seemed to work out OK.

This wound up being the list of Ubuntu packages I needed to install to get your project to build:
* build-essential
* libhdf5-dev
* python3
* python3-dev
* python3-cffi
* libseccomp-dev
* luajit
* libluajit-5.1-dev

I needed to install these additional packages to build syscall_intercept:
* cmake
* libcapstone-dev
* pkg_config

One big obstacle I hit while building your project is that Debian/Ubuntu's default install location for the hdf5 library and header files is different than what seems to be expected by your application. I had to include some additional search location flags for `CC` and `LD` to be able to compile and link the application properly. A quick Google search seems to indicate that maybe these paths changed in 18.04 of Ubuntu? Not sure.

**Comment by lucasvr** [comment]
This is very good news! :)

Does the Debian/Ubuntu package for HDF5 ship with a pkgconfig file? How does your change to LD/CXXFLAGS look like?

**Comment by snhardin** [comment]
> How does your change to LD/CXXFLAGS look like?

I committed my changes here: https://github.com/snhardin/hdf5-udf/commit/87768b3084656019590b42b79fa6e383f67aeadb

> Does the Debian/Ubuntu package for HDF5 ship with a pkgconfig file?

I believe so? If I run the following commands, I get the following output:
```bash
root@437e1d239b32:/# pkg-config --cflags hdf5
-I/usr/include/hdf5/serial
root@437e1d239b32:/# pkg-config --libs hdf5  
-L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5
```

**Comment by lucasvr** [comment]
Please check if `$(pkg-config --libs hdf5-serial hdf5)` works for you. That
will be more portable than hardcoding the path to the headers and
libraries. Thanks!

Em sáb, 3 de out de 2020 16:52, Scott Hardin <notifications@github.com>
escreveu:

**Comment by lucasvr** [comment]
Please check if `$(pkg-config --libs hdf5-serial hdf5)` works for you. That will be more portable than hardcoding the path to the headers and libraries. Thanks!

**Comment by snhardin** [comment]
Yup, that worked. Thanks! It's been an awfully long time since I've had to mess around with building a C/C++ application, so I'm pretty rusty. https://github.com/snhardin/hdf5-udf/commit/a0f57de1bd2f6f71d04a94cb6cb67513d79949d2

**Comment by lucasvr** [comment]
@snhardin please let me know how it goes and if I can be of any help to you :)

**Comment by snhardin** [comment]
@lucasvr is syscall_intercept a runtime dependency, or is it only required for building the project?

Not having syscall_intercept already packaged somewhere is a little bit of a problem. I'm hesitant to try and lump the syscall_intercept library in with the hdf5-udf package.

If you guys are planning on hosting this in a PPA, you can host the syscall_intercept package as well (they have their own deb package) and set your hdf5-udf debian package to depend on that. I think that this would be a good alternative, although that really depends on how you plan to distribute this to others. Let me know what you think.

**Comment by lucasvr** [comment]
@snhardin it's a runtime dependency -- `libhdf5-udf-sandbox.so` uses it. Note that we don't explicitly install `libhdf5-udf-sandbox.so` on `make install`. rather, we pack it inside `libhdf5-udf.so` (which we do install) and extract it when we need it.

My original intention was to simply build .deb packages and host them on GitHub. Based on the constraints it looks like it would be best to host a PPA, though. I've no experience creating a Debian repository, but I'm sure there must be tools out there to automate it to a good extent.

**Comment by snhardin** [comment]
Here's an idea -- perhaps we can just statically link syscall_intercept for use in the .deb file? You'd have to adhere by their license, but that would eliminate the need for a PPA. 🤔

Edit: Also, any advice for running the samples? I'm not sure what I should be setting `HDF5_PLUGIN_PATH` to. I've tried `export HDF5_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial` and `export HDF5_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/` among others, but always wind up segfaulting.

**Comment by lucasvr** [comment]
I have thought of that as well, but I haven't tested that approach yet. Let me do that today and I'll come back to you to tell if the program behaves as expected afterwards. The thing is that syscall_intercept executes some code when it's loaded into the process' memory, and I don't know if they'll still execute when the code is statically linked.

As for HDF5_PLUGIN_PATH: you just have to set it to the directory where `libhdf5-udf.so` is found. You shouldn't get a segfault if that variable is incorrectly set, though. Could you test something for me? Try to build the code with `make OPT_SANDBOX=0` and try to run one of the samples again. Assuming that it works with that change, could you tell me which version of Glibc you're running on your computer?

To run the samples, you can follow these steps after `make install`:
```
cd examples
make files
make readh5
hdf5-udf example-socket.h5 example-socket.cpp Tux:60x80:int32
./readh5 example-socket.h5 Tux
```

You can also run a more simple example that does not retrieve data over the internet, such as this one:
```
hdf5-udf example-add_datasets.h5 example-add_datasets.cpp
./readh5 example-add_datasets.h5 VirtualDataset
```

Note that this one will print some sequence of concatenated numbers to the console that will look like garbage:

```
Reading dependency dataset Dataset1
Reading dependency dataset Dataset2
024681012141618202224262830323436384042444648505254565860626466687072747678808284868890929496983032343638404244464850525456586062646668707274767880828486889092949698100102104106108110112114116118120122124126128
60626466687072747678808284868890929496981001021041061081101121141161181201221241261281301321341361381401421441461481501521541561589092949698100102104106108110112114116118120122124126128130132134136138140142144146148150152154156158160162164166168170172174176178180182184186188
...
```

Also note that it's possible to `export HDF5_PLUGIN_PATH=/path/to/hdf5-udf/src` and to run the main program straight from `src`.

**Comment by lucasvr** [comment]
For reference, the examples build and run on Docker using ubuntu:18.04 with syscall_intercept just fine. If you can give me more information regarding the distro you're running then I can look into reproducing the crash.

**Comment by lucasvr** [comment]
@snhardin please note that I've pushed some changes to the build script in the master branch. I have made the move to use `pkg-config --cflags/--libs hdf5`. Please let me know if it works for you.

Also, the version of libhdf5-dev I installed through apt-get on Ubuntu 18.04 came with a compatibility name so that `hdf5 -> hdf5-serial`, so I haven't hdf5-serial by default. Thanks!

**Comment by lucasvr** [comment]
All right, I've tested and the code behaves fine when linked against a static version of libsyscall_intercept on my distro -- but it doesn't work on Ubuntu. If I replace `-lsyscall_intercept` with `/usr/lib/libsyscall_intercept.a` (and ditto for `libcapstone`) the resulting `libhdf5-udf-sandbox.so` does not seem to incorporate the objects from the archive.

I think that going down the path of hosting a PPA may not be a bad idea after all.

**Comment by lucasvr** [comment]
@snhardin, I've just implemented support for creating RPM files under https://github.com/lucasvr/hdf5-udf/commit/e66079149ad54a51eead139cbecc4dbd7d289ca9. The commit includes the spec file and a Dockerfile that builds both syscall_intercept and HDF5-UDF. Feel free to follow the same approach -- I can figure how to serve the files on a PPA afterwards. Thanks!

**Comment by snhardin** [comment]
Hey @lucasvr. Thanks for the RPM reference. I'll try to follow this when creating the DEB package.

> Could you test something for me? Try to build the code with `make OPT_SANDBOX=0` and try to run one of the samples again. Assuming that it works with that change, could you tell me which version of Glibc you're running on your computer?

I'll try this for you and let you know. Thanks for the info on running the samples.

**Comment by lucasvr** [comment]
Great, thanks for the update! Also, please feel free to share whatever you have with regard to the DEB stuff if you need help testing it.

**Comment by snhardin** [comment]
Hey @lucasvr. Something I've noticed while creating the DEB package is that the version of `install` for Ubuntu 20.04 doesn't appear to support some syntax that you use in one of your Makefiles? I had to make the change here to get it to build: https://github.com/snhardin/hdf5-udf/commit/cd668eb90f0ebdb6172a5303e0342c15570df51e.

**Comment by lucasvr** [comment]
Ah, no worries, @snhardin. That's actually a bash-ism. Ubuntu uses Dash as its default shell, and I presume it doesn't implement support for {a,b,c}. Please go ahead with that modification, I'll merge it as-is when the PR is ready.

**Comment by snhardin** [comment]
@lucasvr Want to do me a favor? Could you please add the `hacktoberfest-accepted` tag to the PR so it'll count for this month?

**Comment by lucasvr** [comment]
@snhardin done. Thanks again for your help!
