### ISSUE TITLE
Support bytecodes that exceed the dataset size

### ISSUE THREAD

**Issue by lucasvr** [lucasvr/hdf5-udf#7]
Currently, `hdf5-udf` writes the UDF in the HDF5 file by:

1. Registering the UDF filter
2. Declaring a dataset with resolution `N x M x sizeof(datatype)`
3. Trying to fit the payload (bytecode and metadata) in the memory allocated for that dataset 
4. Calling `H5Dwrite` with that chunk of memory

When the dataset is big enough it's likely that the payload will fit just fine. Take a small vector, however, and it will not. If we try to workaround by allocating a larger chunk of memory on step 2, then it's possible that `H5Dwrite`  truncates the payload before it reaches the UDF filter write callback.

A quick exercise in the past has shown that large pieces of data cannot be passed as argument to `H5Pset_filter`, either. Ideally, we should find a way to make the payload reach the UDF filter callback intact. As an alternative, we could look into simply encoding the memory address where the payload is found in the very first bytes and pass that to `H5Dwrite` / `H5Pset_filter`.

**Comment by iFrogHop2Worlds** [comment]
Can I take a shot at this?

**Comment by lucasvr** [comment]
Absolutely!

**Comment by lucasvr** [comment]
This one is associated with a bug in HDF5. I've opened a [ticket](https://forum.hdfgroup.org/t/hdf5-crashes-with-inefficient-compressors) on their forum and will be looking into a resolution for the problem. There's no way to work around the problem from our side, though, so I'm closing this issue for good.
